---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-load
  labels:
    app: redis-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-load
  template:
    metadata:
      labels:
        app: redis-load
    spec:
      containers:
      - name: redis
        image: kaleoum/redis:d26
        args:
          - -c
          - python3 -u redis.py
        command:
          - /bin/bash 
        env:
          - name: HOST
            value: 'redis-cart.gcp.svc'
         
      

