---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-load-k6
  labels:
    app: redis-load-k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-load-k6
  template:
    metadata:
      labels:
        app: redis-load-k6
    spec:
      containers:
      - name: redis
        image: kaleoum/redis-load:c27
        args:
          - -c
          - python3 redis.py
        command:
          - /bin/bash 
        env:
          - name: HOST
            value: 'redis-cart.gcp.svc'
      

